//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE450Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfn_CaffeineConsumption
    {
        public int cfn_ID { get; set; }
        public System.DateTime cfn_DateTime { get; set; }
        public int cfn_cft_ID { get; set; }
        public string cfn_aur_id { get; set; }
        public int cfn_number { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
