//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE450Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cft_CaffeineType
    {
        public int cft_id { get; set; }
        public double cft_amount { get; set; }
        public double cft_size { get; set; }
        public int prd_Product { get; set; }
    
        public virtual prd_Product prd_Product1 { get; set; }
    }
}
