//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE450Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class chn_ChainAnalysis
    {
        public chn_ChainAnalysis()
        {
            this.bhv_Behavior = new HashSet<bhv_Behavior>();
            this.emt_Emotions = new HashSet<emt_Emotions>();
            this.gft_GoalsForTomorrow = new HashSet<gft_GoalsForTomorrow>();
            this.imc_ImmediateConsequences = new HashSet<imc_ImmediateConsequences>();
            this.ltc_LongTermConsequences = new HashSet<ltc_LongTermConsequences>();
            this.ltg_LongTermGoal = new HashSet<ltg_LongTermGoal>();
            this.stg_ShortTermGoals = new HashSet<stg_ShortTermGoals>();
            this.tht_Thought = new HashSet<tht_Thought>();
            this.vul_Vulnerability = new HashSet<vul_Vulnerability>();
            this.wtp_WaysToPrevent = new HashSet<wtp_WaysToPrevent>();
        }
    
        public int chn_ID { get; set; }
        public string chn_aur_id { get; set; }
        public string chn_ProblemBehavior { get; set; }
        public System.DateTime chn_DateAndTime { get; set; }
        public string chn_Location { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<bhv_Behavior> bhv_Behavior { get; set; }
        public virtual ICollection<emt_Emotions> emt_Emotions { get; set; }
        public virtual ICollection<gft_GoalsForTomorrow> gft_GoalsForTomorrow { get; set; }
        public virtual ICollection<imc_ImmediateConsequences> imc_ImmediateConsequences { get; set; }
        public virtual ICollection<ltc_LongTermConsequences> ltc_LongTermConsequences { get; set; }
        public virtual ICollection<ltg_LongTermGoal> ltg_LongTermGoal { get; set; }
        public virtual ICollection<stg_ShortTermGoals> stg_ShortTermGoals { get; set; }
        public virtual ICollection<tht_Thought> tht_Thought { get; set; }
        public virtual ICollection<vul_Vulnerability> vul_Vulnerability { get; set; }
        public virtual ICollection<wtp_WaysToPrevent> wtp_WaysToPrevent { get; set; }
    }
}
