//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE450Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class pre_PredefinedEmotion
    {
        public pre_PredefinedEmotion()
        {
            this.eml_EmotionLog = new HashSet<eml_EmotionLog>();
            this.emt_Emotions = new HashSet<emt_Emotions>();
        }
    
        public int pre_ID { get; set; }
        public string pre_Emotion { get; set; }
    
        public virtual ICollection<eml_EmotionLog> eml_EmotionLog { get; set; }
        public virtual ICollection<emt_Emotions> emt_Emotions { get; set; }
    }
}
