//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE450Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class wtp_WaysToPrevent
    {
        public int wtp_order { get; set; }
        public int wtp_chn_id { get; set; }
        public string wtp_WayToPrevent { get; set; }
    
        public virtual chn_ChainAnalysis chn_ChainAnalysis { get; set; }
    }
}
