//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE450_Sleep_Tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class eht_EmotionLogThought
    {
        public int eth_order { get; set; }
        public int eth_eml_ID { get; set; }
        public string eth_Thought { get; set; }
    }
}
