//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE450_Sleep_Tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class eml_EmotionLog
    {
        public int eml_ID { get; set; }
        public System.DateTime eml_logTime { get; set; }
        public string eml_aur_id { get; set; }
        public int eml_pre_id { get; set; }
        public short eml_intensity { get; set; }
        public string eml_trigger { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual pre_PredefinedEmotion pre_PredefinedEmotion { get; set; }
    }
}
