//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE450_Sleep_Tracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SleepMonitorEntities : DbContext
    {
        public SleepMonitorEntities()
            : base("name=SleepMonitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<awk_NighttimeAwakenings> awk_NighttimeAwakenings { get; set; }
        public virtual DbSet<bhv_Behavior> bhv_Behavior { get; set; }
        public virtual DbSet<cfn_CaffeineConsumption> cfn_CaffeineConsumption { get; set; }
        public virtual DbSet<cft_CaffeineType> cft_CaffeineType { get; set; }
        public virtual DbSet<chn_ChainAnalysis> chn_ChainAnalysis { get; set; }
        public virtual DbSet<ctr_ConcentrationLog> ctr_ConcentrationLog { get; set; }
        public virtual DbSet<eht_EmotionLogThought> eht_EmotionLogThought { get; set; }
        public virtual DbSet<eml_EmotionLog> eml_EmotionLog { get; set; }
        public virtual DbSet<emt_Emotions> emt_Emotions { get; set; }
        public virtual DbSet<exi_ExerciseIntensity> exi_ExerciseIntensity { get; set; }
        public virtual DbSet<exr_Exercise> exr_Exercise { get; set; }
        public virtual DbSet<ext_ExerciseTypes> ext_ExerciseTypes { get; set; }
        public virtual DbSet<ftg_FatigueLevels> ftg_FatigueLevels { get; set; }
        public virtual DbSet<gft_GoalsForTomorrow> gft_GoalsForTomorrow { get; set; }
        public virtual DbSet<gsr_GlobalSuggestions> gsr_GlobalSuggestions { get; set; }
        public virtual DbSet<imc_ImmediateConsequences> imc_ImmediateConsequences { get; set; }
        public virtual DbSet<ltc_LongTermConsequences> ltc_LongTermConsequences { get; set; }
        public virtual DbSet<ltg_LongTermGoal> ltg_LongTermGoal { get; set; }
        public virtual DbSet<prd_Product> prd_Product { get; set; }
        public virtual DbSet<pre_PredefinedEmotion> pre_PredefinedEmotion { get; set; }
        public virtual DbSet<rwd_Rewards> rwd_Rewards { get; set; }
        public virtual DbSet<slp_SleepLog> slp_SleepLog { get; set; }
        public virtual DbSet<stg_ShortTermGoals> stg_ShortTermGoals { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tht_Thought> tht_Thought { get; set; }
        public virtual DbSet<vul_Vulnerability> vul_Vulnerability { get; set; }
        public virtual DbSet<wtp_WaysToPrevent> wtp_WaysToPrevent { get; set; }
    }
}
