//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE450_Sleep_Tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class ftg_FatigueLevels
    {
        public int ftg_ID { get; set; }
        public short ftg_level { get; set; }
        public System.DateTime ftg_logTime { get; set; }
        public string ftg_aur_id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
