//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE450_Sleep_Tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class rwd_Rewards
    {
        public string rwd_aur_id { get; set; }
        public string rwd_RewardName { get; set; }
        public Nullable<int> rwd_gsr_id { get; set; }
        public Nullable<int> rwd_NumCheckMarksRequired { get; set; }
        public int rwd_ID { get; set; }
    
        public virtual gsr_GlobalSuggestions gsr_GlobalSuggestions { get; set; }
        public virtual rwd_Rewards rwd_Rewards1 { get; set; }
        public virtual rwd_Rewards rwd_Rewards2 { get; set; }
    }
}
